# Generated by Django 2.0.3 on 2018-04-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone',
            new_name='Semester',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Class',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='TotalCredits',
            field=models.IntegerField(default=0),
        ),
    ]
