# Generated by Django 2.0.3 on 2018-04-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180402_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(default='', max_length=100)),
                ('SubCategory', models.CharField(default='', max_length=100)),
                ('DocType', models.CharField(default='', max_length=100)),
                ('File', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
