# Generated by Django 2.0.3 on 2018-04-11 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180411_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadpage',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='leadpage',
            name='DocType',
        ),
        migrations.RemoveField(
            model_name='leadpage',
            name='SubCategory',
        ),
    ]
