# Generated by Django 2.0.3 on 2018-06-23 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0008_leadpage_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='NatPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.IntegerField(choices=[(0, 'Select:'), (1, 'NCC'), (2, 'NSS')], default=0, max_length=100)),
                ('SubCategory', models.IntegerField(choices=[(0, 'Select:'), (1, 'C certificate(os performance)'), (2, 'Best NSS Volunteer Awardee(University Level)'), (3, 'Participation in National Integration Camp'), (4, 'Participation in Pre-Republic Day Parade Camp'), (5, 'Best NSS Awardee(State Level/National Level)'), (6, 'Participation in Republic Day Parade Camp'), (7, 'International Youth Exchange Programme'), (7, 'Others')], default=0, max_length=100)),
                ('DocType', models.IntegerField(choices=[(0, 'Select'), (1, 'College Events'), (2, 'Zonal Events'), (3, 'State/ University Events'), (4, 'National Events'), (5, 'International Events')], default=0, max_length=100)),
                ('File', models.FileField(blank=True, null=True, upload_to='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='leadpage',
            name='Category',
            field=models.IntegerField(choices=[(0, 'Select:'), (1, 'Student Professional Societies (IEEE,IET, ASME, SAE,NASA etc.)'), (2, 'College Association Chapters (Mechanical, Civil,Electrical etc.)'), (3, 'Festival & Technical Events(College approved)'), (4, 'Hobby Clubs'), (5, 'Special Initiatives(Approval from College and University is mandatory)')], default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='leadpage',
            name='DocType',
            field=models.IntegerField(choices=[(0, 'Select:'), (1, '(a) Certificate'), (2, '(b) Letter from Authorities'), (3, '(c) Appreciation recognition letter'), (4, '(d)Documentary evidence'), (5, '(e) Legal Proof'), (6, 'Others')], default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='leadpage',
            name='SubCategory',
            field=models.IntegerField(choices=[(0, 'Select:'), (1, 'Core coordinator'), (2, 'Sub coordinator'), (3, 'Volunteer')], default=0, max_length=100),
        ),
    ]
