# Generated by Django 2.0.3 on 2018-06-24 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180624_0043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadpage',
            old_name='user',
            new_name='user1',
        ),
    ]
