# Generated by Django 2.0.3 on 2018-07-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20180701_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='natpage',
            name='Category',
            field=models.IntegerField(choices=[(0, 'Select:'), (1, 'NCC'), (2, 'NSS')], default=0),
        ),
        migrations.AlterField(
            model_name='natpage',
            name='DocType',
            field=models.IntegerField(choices=[(0, 'Select'), (1, 'College Events'), (2, 'Zonal Events'), (3, 'State/ University Events'), (4, 'National Events'), (5, 'International Events')], default=0),
        ),
        migrations.AlterField(
            model_name='natpage',
            name='SubCategory',
            field=models.IntegerField(choices=[(0, 'Select:'), (1, 'C certificate(os performance)'), (2, 'Best NSS Volunteer Awardee(University Level)'), (3, 'Participation in National Integration Camp'), (4, 'Participation in Pre-Republic Day Parade Camp'), (5, 'Best NSS Awardee(State Level/National Level)'), (6, 'Participation in Republic Day Parade Camp'), (7, 'International Youth Exchange Programme'), (7, 'Others')], default=0),
        ),
    ]
