# Generated by Django 2.0.3 on 2018-07-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20180701_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultpage',
            name='Position',
            field=models.IntegerField(choices=[(0, 'Select:'), (1, 'First'), (2, 'Second'), (3, 'Third')], default=0),
        ),
        migrations.AlterField(
            model_name='cultpage',
            name='DocType',
            field=models.IntegerField(choices=[(0, 'Select:'), (1, '(a) Certificate'), (2, '(b) Letter from Authorities'), (3, '(c) Appreciation recognition letter'), (4, '(d)Documentary evidence'), (5, '(e) Legal Proof'), (6, 'Others')], default=0),
        ),
    ]
