# Generated by Django 2.0.3 on 2018-07-01 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0013_auto_20180701_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.IntegerField(choices=[(0, 'Select:'), (1, 'Tech Fest, Tech Quiz'), (2, 'MOOC with final assessment certificate'), (3, 'Competitionsconducted by Professional Societies - (IEEE,IET, ASME, SAE,NASA etc.)'), (4, 'Attending Full timeConference/Seminars /Exhibitions/Workshop/ STTPconducted at IITs/NITs'), (5, 'Paper presentation/publication at IITs/NITs'), (6, 'Poster Presentationat IITs /NITs'), (7, 'Industrial Training/Internship (atleastfor 5 full days)'), (8, 'Industrial/Exhibition visits'), (9, 'Foreign Language Skill (TOFEL/IELTS/BEC exams etc.)')], default=0)),
                ('Level', models.IntegerField(choices=[(0, 'Select'), (1, 'College Events'), (2, 'Zonal Events'), (3, 'State/ University Events'), (4, 'National Events'), (5, 'International Events')], default=0)),
                ('DocType', models.IntegerField(choices=[(0, 'Select:'), (1, '(a) Certificate'), (2, '(b) Letter from Authorities'), (3, '(c) Appreciation recognition letter'), (4, '(d)Documentary evidence'), (5, '(e) Legal Proof'), (6, 'Others')], default=0)),
                ('File', models.FileField(blank=True, null=True, upload_to='')),
                ('user4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='cultpage',
            old_name='SubCategory',
            new_name='Level',
        ),
    ]
