# Generated by Django 2.0.3 on 2018-07-02 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0015_auto_20180702_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.IntegerField(choices=[(0, 'Select:'), (1, 'Start-up Company –Registered legally'), (2, 'Patent-Filed'), (3, 'Patent-Published'), (4, 'Patent-Approved'), (5, 'Patent-Licensed'), (6, 'Awards forProducts developed'), (7, 'Innovative technologies developed and used by industries/users'), (8, 'Got venture capital funding for innovative ideas/products'), (9, 'Startup Employment (Offering jobs to two persons less than Rs. 15000/- per month)'), (10, 'Societal innovations')], default=0)),
                ('DocType', models.IntegerField(choices=[(0, 'Select:'), (1, '(a) Certificate'), (2, '(b) Letter from Authorities'), (3, '(c) Appreciation recognition letter'), (4, '(d)Documentary evidence'), (5, '(e) Legal Proof'), (6, 'Others')], default=0)),
                ('File', models.FileField(blank=True, null=True, upload_to='')),
                ('user5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
