# Generated by Django 2.0.3 on 2018-07-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_entrepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepage',
            name='Category',
            field=models.IntegerField(choices=[(0, 'Select:'), (1, 'Start-up Company –Registered legally'), (2, 'Patent-Filed'), (3, 'Patent-Published'), (4, 'Patent-Approved'), (5, 'Patent-Licensed'), (6, 'Prototype developed and tested'), (7, 'Awards for Products developed'), (8, 'Innovative technologies developed and used by industries/users'), (9, 'Got venture capital funding for innovative ideas/products'), (10, 'Startup Employment (Offering jobs to two persons less than Rs. 15000/- per month)'), (11, 'Societal innovations')], default=0),
        ),
    ]
