# Generated by Django 2.0.3 on 2018-08-02 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0021_auto_20180802_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='NatPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TwoYears', models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], default=0)),
                ('Category', models.IntegerField(choices=[(0, 'Select:'), (1, 'NCC'), (2, 'NSS')], default=0)),
                ('SubCategory', models.IntegerField(choices=[(0, 'Select:'), (1, 'C certificate(os performance)'), (2, 'Best NSS Volunteer Awardee(University Level)'), (3, 'Participation in National Integration Camp'), (4, 'Participation in Pre-Republic Day Parade Camp'), (5, 'Best NSS Awardee(State Level/National Level)'), (6, 'Participation in Republic Day Parade Camp'), (7, 'International Youth Exchange Programme'), (8, 'Others')], default=0)),
                ('DocType', models.IntegerField(choices=[(0, 'Select:'), (1, '(a) Certificate'), (2, '(b) Letter from Authorities'), (3, '(c) Appreciation recognition letter'), (4, '(d)Documentary evidence'), (5, '(e) Legal Proof'), (6, 'Others')], default=0)),
                ('File', models.FileField(blank=True, null=True, upload_to='')),
                ('user2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
